comments:
  EndOfSentenceFormat:
    active: true
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: true
  #UndocumentedPublicProperty:
  #  active: true
complexity:
  LongParameterList:
    functionThreshold: 8 #updated
  TooManyFunctions:
    ignoreDeprecated: true
    ignorePrivate: true
    ignoreOverridden: true
    thresholdInFiles: 20
    #thresholdInClasses: 20
    #thresholdInInterfaces: 20
    #thresholdInObjects: 20
    #thresholdInEnums: 20


style:
  ForbiddenComment:
    allowedPatterns: 'TODO:'
  WildcardImport:
    active: false
  UnusedPrivateMember:
    active: false
  MagicNumber:
    active: false

naming:
  VariableNaming:
    active: false

exceptions:
  SwallowedException:
    active: false