name: Checking coverage with Gradle

on:
  push:
    branches: [ feature/end_to_end_example ]

jobs:
  build:
    #strategy:
    #  fail-fast: false
    #  matrix:
    #    os: [ windows-latest, ubuntu-latest, macos-latest ]
    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x koverVerify  # skipping koverVerify to not fail if the coverage has lowered

      - name: Archive framework test report
        uses: actions/upload-artifact@v3
        with:
          name: ReportFramework
          path: framework/build/kover/

      - name: Archive domain test report
        uses: actions/upload-artifact@v3
        with:
          name: ReportDomain
          path: domain/build/kover/

      - name: Archive dsl test report
        uses: actions/upload-artifact@v3
        with:
          name: ReportDsl
          path: dsl/build/kover/

      - name: Archive explanation test report
        uses: actions/upload-artifact@v3
        with:
          name: ReportExplanation
          path: explanation/build/kover/