name: Documentation
on:
  push:
    branches:
      - feature/documentation_pages

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: planning/build
          branch: gh-pages
