name: Documentation
on:
  push:
    branches:
      - feature/documentation_pages

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: ./gradlew dokkaHtml
      - uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: build/dokkaHtmlMultiModule