name: Documentation
on:
  push:
    branches:
      - feature/documentation_pages

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: ./gradlew dokkaHtml
      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: planning/build